language: php
sudo: false
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master

install:
  - travis_retry composer update -n --prefer-dist --prefer-stable

script:
  - ./vendor/bin/phpunit -v

jobs:
  allow_failures:
    - php: nightly

  include:
    # Tests the lowest set of dependencies
    - php: 7.1
      env: LOWEST SYMFONY_DEPRECATIONS_HELPER=weak
      install:
        - travis_retry composer update -n --prefer-lowest --prefer-stable --prefer-dist

    # Test against latest Symfony 4.3 stable
    - php: 7.3
      env: SYMFONY_REQUIRE="4.3.*"
      install:
        - composer require --dev symfony/messenger --no-update
        - travis_retry composer update -n --prefer-dist --prefer-stable

    # Test against latest Symfony 4.4 dev
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - composer require --dev symfony/messenger --no-update
        - travis_retry composer update -n --prefer-dist

    # Test against latest Symfony 5.2 dev
    - php: 7.4
      env: SYMFONY_REQUIRE="5.2.*"
      install:
        - composer require --dev symfony/messenger --no-update
        - travis_retry composer update -n --prefer-dist

    # Test dev versions
    - php: 7.4
      if: type = cron
      env: DEV
      install:
        - travis_retry composer update -n --prefer-dist

    # Test against PHP 8
    - php: nightly
      env: SYMFONY_DEPRECATIONS_HELPER=weak
      before_install:
        - composer config platform.php 7.4.99
        - composer remove --dev doctrine/orm --no-update
      install:
        - travis_retry composer update -n --prefer-dist

    - stage: Coverage
      php: 7.3
      install:
        - composer require --dev "symfony/messenger" --no-update
        - travis_retry composer update -n --prefer-dist
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
#      after_script:
#        - php ./vendor/bin/coveralls -v
